project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!posts/PSYC_2002_01_jspsych/jspsych_tutorial"

website:
  title: "CrumpLabExampleBlog"
  navbar:
    left:
      - changes.qmd
      - text: More Pages
        menu:
          - pages/new_page.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/CrumpLab/CrumplabExampleBlog
      - icon: twitter
        href: https://twitter.com/MattCrumpLab
format:
  html:
    theme: minty
    css: styles.css

editor: visual

