project:
  type: website
  output-dir: docs

website:
  title: "CrumpLabExampleBlog"
  navbar:
    left:
      - changes.qmd
      - text: More Pages
        menu:
          - text: Basic Page
            file: pages/basic_stuff.html
    right:
      - about.qmd
      - icon: github
        href: https://github.com/CrumpLab/CrumplabExampleBlog
      - icon: twitter
        href: https://twitter.com/MattCrumpLab
format:
  html:
    theme: minty
    css: styles.css

editor: visual

